name: Deploy Next.js Blog Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server (via SSH)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_PORT: ${{ secrets.VPS_PORT }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $VPS_PORT -H "$VPS_HOST" >> ~/.ssh/known_hosts

          ssh -p $VPS_PORT -i ~/.ssh/id_rsa $VPS_USER@$VPS_HOST << 'EOF'
            set -e

            echo "========== Deploying Next.js Blog =========="
            cd /var/www/beramal-new/blog
            git config --global --add safe.directory /var/www/beramal-new/blog
            git pull 
            
            # Install dependensi & build project Next.js
            yarn install --frozen-lockfile
            yarn build

            # Restart proses PM2
            pm2 restart blog-beramal --update-env
          EOF